### ISSUE TITLE
[Lua Specific Bug] Conditionals

### ISSUE THREAD

**Issue by theoriginalbit** [espertus/blockly-lua#10]
Again this comes down to how odd Lua is, but with Lua a conditional can be anything, not just a boolean. `false` and `nil` both are resolved to `false` any other value resolves to `true`.

``` Lua
if "hello" then
  print("This line will always print")
else
  print("You'll never see this line")
end
```

As such any logic and loops may need to be updated to reflect this... Your thoughts are appreciated since this is primarily a "feature" to Lua and not general programming.

Oh also the ternary I would like to point out the following problem in Lua that you may want to allow for in some way... The ternary operator does not exist in Lua, they've provided us with the following logic `[condition] and [value-if-true] or [value-if-false]` however since this logic (which is the closest we can ever get to a ternary) falls under the rules of boolean logic it fails when the `value-if-true` is `false` or `nil`, basic example

``` Lua
print("hello" and false or "h")
```

the above code will print `h` because the true value was false.

**Comment by espertus** [comment]
I think the existing code generation is correct, although it may sometimes
require more blocks than strictly necessary.  I'm okay with that.

I use the ternary trick in the Lua code generator for the Logic -> test
block.
