### ISSUE TITLE
[Suggestion] Better coding habit promotion

### ISSUE THREAD

**Issue by theoriginalbit** [espertus/blockly-lua#5]
This is probably the most complex of all my suggestions to implement, but here goes with the suggestion

I think that a complete overhaul of the generator would be handy in order to promote better coding habits, especially since this is a learning tool. The main coding habit that I'm referring to is [localisation](http://www.lua.org/pil/4.2.html) of variables and functions so as to not pollute the environment, also in Lua local variables are way more efficient due to being stored in registers, instead of the heap.

The main difficulty of implementing this is that local variables must be defined before they're referenced, for example

``` Lua
local output = "Hello world"

local function foo()
  bar() -- this will error, bar has not been defined
end

local function bar()
  print(output) -- this works, output is defined
end

foo() -- this works, foo is defined
```

would error the moment it tried to call bar within foo. this is because at compile time there is no local variable/name `bar`, so it is setup to look in the global space therefore never seeing the local bar function... it also causes a problem if there was a global variable or function named bar, as it would call that instead.

The code generator would need to know these rules and then be able to identify order and output. It would also get a little more complicated when they attempted recursion of cyclic recursion, as this would error

``` Lua
local function a()
  a() -- a isn't defined
end

a()
```

and so would this (due to the previous rule)

``` Lua
local function a()
  b() -- b isn't defined
end

local function b()
  a()
end

a()
```

the only way to solve these problems are like so

``` Lua
local a
function a()
  a()
end
a()
```

and this

``` Lua
local a, b

function a()
  b()
end

function b()
  a()
end

a()
```

hope all that made sense.

**Comment by espertus** [comment]
You're right, of course, but it's not something I feel able to take on.

**Comment by theoriginalbit** [comment]
Yeah unfortunately I do not have the require domain knowledge of Blockly (and JS it seems) to be able add it, I've had a look through the generator code and such quickly the other day (in-between Uni assignments), but there was too much I didn't understand about it to be able to make the changes myself and then PR.
