### ISSUE TITLE
[Suggestion] Naming validation

### ISSUE THREAD

**Issue by theoriginalbit** [espertus/blockly-lua#6]
I feel that blockly-lua should not allow users to name variables and functions the same... I obviously know that there is no way to validate naming variables the same as you'd be unaware if they're wanting to assign a new number or create a new variable (maybe new blocks, one creates, one assigns?) but I definitely think you should have some validation to stop them doing this (FYI Lua allows it, especially since there is no type checking in Lua)

``` Lua
local foo = "bar"
local foo() -- the above variable no longer exists
  return "bar"
end
```

also having a blacklist of system functions that cannot have a variable or function with the same name as would be good, such as `read`

**Note:** I feel that if there were to be a change in the way variables worked, i.e. a block to create and assign a variable and a different block to reassign it later could also greatly help with #5 as you could also take into consideration things such as scope (which has the added bonus of teaching them about scope) for example if they tried this

``` Lua
local bar = " world"

local function foo()
  local bar = "hello"
  write(bar)
end

foo()
print(bar)
```

it would be allowed due to scope, however there could be a "warning" saying that they have a naming conflict and only the one inside the function will be used when in the function.
However in contrast if they tried this, it would obviously have to error telling them of a name conflict

``` Lua
local function foo()
  local bar = "hello"
  local bar = " world"
  local foo = "!" -- this is allowed though foo isn't defined when this function is compiled ;P
end

foo()
```

**Comment by theoriginalbit** [comment]
**Note 2:** if you wish to get a list of all the function and variable names in CC/Lua, you can use the following code on any computer

``` Lua
local function quickSleep()
  os.queueEvent('d')
  coroutine.yield()
end

local output = {}

local function iterateTable(t, id)
  print("Iterating table "..id)
  for k,v in pairs(t) do
    local line = (id ~= "_G" and id.."." or "")..tostring(k)
    if type(v) == "table" and tostring(k) ~= "_G" then
      quickSleep()
      iterateTable(v, k)
    elseif type(v) == "function" then
      local value = "function: "..line
      table.insert(output, value)
      quickSleep()
    elseif tostring(k) ~= "_G" then
      local value = "variable: "..line
      table.insert(output, value)
      quickSleep()
    end
  end
end

iterateTable(_G, "_G")
table.sort(output)
local outputFile = fs.open("output", "w")
outputFile.write(table.concat(output, '\n'))
outputFile.close()
```

**Comment by espertus** [comment]
On Mon, Nov 4, 2013 at 7:34 PM, Josh Asbury notifications@github.comwrote:

> I feel that blockly-lua should not allow users to name variables and
> functions the same...
> 
> We call this function [
> https://github.com/espertus/blockly-lua/blob/master/core/variables.js#L140]
>  to create variable names, which forces them to be unique.  I tried
> creating a program with a function named "foo" and a variable named "foo",
> and one was renamed "foo2".
> 
> also having a blacklist of system functions that cannot have a variable or
> function with the same name as would be good, such as read

This exists.  See:
https://github.com/espertus/blockly-lua/blob/master/generators/lua.js#L45

> _Note:_ I feel that if there were to be a change in the way variables
> worked, i.e. a block to create and assign a variable and a different block
> to reassign it later could also greatly help with #5https://github.com/espertus/blockly-lua/issues/5as you could also take into consideration things such as scope
> 
> You can reassign a variable, but you're right that there isn't support for
> scope.  This is a top request for Blockly [
> https://code.google.com/p/blockly/issues/detail?id=69&colspec=ID%20Type%20Status%20Priority%20Reporter%20Owner%20Summary].
> I don't want to take it on independently in Blockly-Lua, although you are
> welcome to.

**Comment by TomSmartBishop** [comment]
Looks like the list for reseved words is not working... I can rename variables to 'else' or 'nil'....

**Comment by espertus** [comment]
@TomSmartBishop, you're right.  I'll take a look.

**Comment by espertus** [comment]
That was the smallest fix I ever made:
https://github.com/espertus/blockly-lua/commit/5ac03bc1143fc01fbf35149eb4ed320d1bf17b66

**Comment by espertus** [comment]
@theoriginalbit, I tried running your code, but I can't remember where files get written on the real external file system.  Any advice?  FWIW, I'm using a Mac.

**Comment by espertus** [comment]
Never mind.  Found it: ~/Library/Application Support/minecraft/saves/
Darn Macs, wanting to hide information from users.

**Comment by theoriginalbit** [comment]
Depends on where you're running the code.

CCDesk
`~/Library/Application Support/ccdesk/computer`

CC-Emulator
`~/Library/Application Support/ccemu/saves/computer`

Minecraft
`~/Library/Application Support/minecraft/saves/[world name]/computer`

Other Minecraft's like FTB and such
`~/Library/Application Support/[instance name]/saves/[world name]/computer`

Servers
`[path to server files]/[world name]/computer`

**Comment by theoriginalbit** [comment]
Well all OSes designed for the "dumb" user hide application data, and its the best design choice they've ever made! could you imagine the average "dumb" user being able to easily access that data!
I've turned on hidden files so I can easily see things like `~/Library` but obviously using cmd + shift + g is the quickest ;)

**Comment by espertus** [comment]
Yeah, but there should have been an option in spotlight search.
How do I turn on hidden files system-wide?

**Comment by espertus** [comment]
Done.

**Comment by theoriginalbit** [comment]
[link](https://www.google.com.au/search?client=safari&rls=en&q=show+hidden+files+mac&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=2B-dUtqhI6GN8QeNvoGYDw)

do I need to get you to read [this](http://www.computercraft.info/forums2/index.php?/topic/12861-searching-google-more-efficiently-for-help-code/)? :P
Wouldn't a condition of working for Google be knowing how to use it? :P

**Comment by espertus** [comment]
Ha.  Thanks for not sending me to lmgtfy.

**Comment by theoriginalbit** [comment]
Haha. Damn, I should have hey, perfect opportunity to! :P

**Comment by TomSmartBishop** [comment]
@espertus Thanks for the fix!
